name: Build HTML
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # 不给权限会报错
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install Dependencies
        run: pnpm install
          
      - name: Build
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      # - name: Sync
      #   run: |
      #     curl -X POST \
      #          -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36" \
      #          -H "Cookie: _tlogin=${{ secrets.SYNC_TOKEN }}" \
      #          --fail \
      #          --show-error \
      #          https://api.travellings.cn/syncUpdate/mlist
