name: Sync to Server
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # 不给权限会报错
    permissions:
      contents: write

    steps:
      - name: Sync
        run: curl https://updates.travellings.cn/update
